# Site Settings
title: Erich Development & IT Tricks
description: Erich Garcia Develpment Tips & Tricks for a IT successfull journey
url: 'https://n3omaster.github.io'
baseurl: '/'
theme_skin: blue

# Tracker
analytics: UA-64168215-7

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development